### ISSUE TITLE
[Empati Tamako] Search and Tagged pages don't display correctly

### ISSUE THREAD

**Issue by lizphillips57** [fukou/tumblr-theme#19]
Hello! I've run into an issue with the Empati theme. The search and tagged pages do not display properly, it ends up looking very squished like this:
![282339890-de6f0a21-806b-4673-b88b-eaa7403665b6](https://github.com/fukou/tumblr-theme/assets/91770641/79489d8f-1721-49c2-a4c9-3661eeef2266)

I've looked at it with Firefox and Google Chrome and it's the same. Also, I wonder if there are supposed to be featured tags displaying under the search bar?

Lovely theme otherwise, thanks for making it! Hopefully the grid feature will be working eventually.

**Comment by fukou** [comment]
Hi @lizphillips57 👋

Thank you for flagging the issue! You're correct; it seems the search and tagged pages are not working properly, and there are currently bugs in the masonry layout.

(I should also fix the grid layout as well, ugh.... I am still looking for the culprit as to why the original posts appear to have a big whitespace instead of photos; will fix this also 🚶‍♂️)

I will definitely update you here again if the theme is fixed.
Thank you again ✨

**Comment by fukou** [comment]
Wait, I forgot to answer your other question @lizphillips57:
> Also, I wonder if there are supposed to be featured tags displaying under the search bar?

Hmm, I don't think so. I believe I did not include this feature for this theme, but I don't mind adding them! It should be easy adding an option for the featured tags under the search bar!

I will keep this in mind after fixing the theme 👍
Thanks!

**Comment by fukou** [comment]
The ticket automatically closes when I finish merging the adjustment to the `main` branch, apparently, lol 🚶‍♂️

I have resolved the issue and added the Featured Tags like you asked. You can preview it [here](https://empati-theme.tumblr.com/).

![image](https://github.com/fukou/tumblr-theme/assets/19899840/388c7e4d-d69a-4250-8377-e1189f9242cc)

To use the updated theme immediately, please reinstall it manually [here](https://github.com/fukou/tumblr-theme/blob/main/empati-theme/empati-theme.html). Otherwise, the updates will be automatically applied to your blog once approved by the Tumblr staff on the theme garden.

Thank you! ✨
Thank you!

**Comment by lizphillips57** [comment]
Wow thank you so much for the quick fix! 🙏 Appreciate it!
